// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dynamo.proto

package dynamo

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	descriptor "github.com/golang/protobuf/protoc-gen-go/descriptor"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DynamoMessageOptions struct {
	// Disables generation for this message
	Disabled bool `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// A compound value that can be used as a Partition Key.
	Partition *Key `protobuf:"bytes,2,opt,name=partition,proto3" json:"partition,omitempty"`
	// A compound value that can be used as a Sort Key.
	Sort *Key `protobuf:"bytes,3,opt,name=sort,proto3" json:"sort,omitempty"`
	// A list of compound values that can be set from other fields.
	CompoundField        []*Key   `protobuf:"bytes,4,rep,name=compound_field,json=compoundField,proto3" json:"compound_field,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamoMessageOptions) Reset()         { *m = DynamoMessageOptions{} }
func (m *DynamoMessageOptions) String() string { return proto.CompactTextString(m) }
func (*DynamoMessageOptions) ProtoMessage()    {}
func (*DynamoMessageOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_67582952f82a4846, []int{0}
}

func (m *DynamoMessageOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamoMessageOptions.Unmarshal(m, b)
}
func (m *DynamoMessageOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamoMessageOptions.Marshal(b, m, deterministic)
}
func (m *DynamoMessageOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamoMessageOptions.Merge(m, src)
}
func (m *DynamoMessageOptions) XXX_Size() int {
	return xxx_messageInfo_DynamoMessageOptions.Size(m)
}
func (m *DynamoMessageOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamoMessageOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DynamoMessageOptions proto.InternalMessageInfo

func (m *DynamoMessageOptions) GetDisabled() bool {
	if m != nil {
		return m.Disabled
	}
	return false
}

func (m *DynamoMessageOptions) GetPartition() *Key {
	if m != nil {
		return m.Partition
	}
	return nil
}

func (m *DynamoMessageOptions) GetSort() *Key {
	if m != nil {
		return m.Sort
	}
	return nil
}

func (m *DynamoMessageOptions) GetCompoundField() []*Key {
	if m != nil {
		return m.CompoundField
	}
	return nil
}

type Key struct {
	Name   string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Fields []string `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	Prefix string   `protobuf:"bytes,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	// defaults to `:` if unset, only used if more than one field is set
	Separator            string   `protobuf:"bytes,4,opt,name=separator,proto3" json:"separator,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Key) Reset()         { *m = Key{} }
func (m *Key) String() string { return proto.CompactTextString(m) }
func (*Key) ProtoMessage()    {}
func (*Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_67582952f82a4846, []int{1}
}

func (m *Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Key.Unmarshal(m, b)
}
func (m *Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Key.Marshal(b, m, deterministic)
}
func (m *Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Key.Merge(m, src)
}
func (m *Key) XXX_Size() int {
	return xxx_messageInfo_Key.Size(m)
}
func (m *Key) XXX_DiscardUnknown() {
	xxx_messageInfo_Key.DiscardUnknown(m)
}

var xxx_messageInfo_Key proto.InternalMessageInfo

func (m *Key) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Key) GetFields() []string {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *Key) GetPrefix() string {
	if m != nil {
		return m.Prefix
	}
	return ""
}

func (m *Key) GetSeparator() string {
	if m != nil {
		return m.Separator
	}
	return ""
}

type DynamoFieldOptions struct {
	Skip                 bool     `protobuf:"varint,1,opt,name=skip,proto3" json:"skip,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type                 *Types   `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DynamoFieldOptions) Reset()         { *m = DynamoFieldOptions{} }
func (m *DynamoFieldOptions) String() string { return proto.CompactTextString(m) }
func (*DynamoFieldOptions) ProtoMessage()    {}
func (*DynamoFieldOptions) Descriptor() ([]byte, []int) {
	return fileDescriptor_67582952f82a4846, []int{2}
}

func (m *DynamoFieldOptions) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DynamoFieldOptions.Unmarshal(m, b)
}
func (m *DynamoFieldOptions) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DynamoFieldOptions.Marshal(b, m, deterministic)
}
func (m *DynamoFieldOptions) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DynamoFieldOptions.Merge(m, src)
}
func (m *DynamoFieldOptions) XXX_Size() int {
	return xxx_messageInfo_DynamoFieldOptions.Size(m)
}
func (m *DynamoFieldOptions) XXX_DiscardUnknown() {
	xxx_messageInfo_DynamoFieldOptions.DiscardUnknown(m)
}

var xxx_messageInfo_DynamoFieldOptions proto.InternalMessageInfo

func (m *DynamoFieldOptions) GetSkip() bool {
	if m != nil {
		return m.Skip
	}
	return false
}

func (m *DynamoFieldOptions) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DynamoFieldOptions) GetType() *Types {
	if m != nil {
		return m.Type
	}
	return nil
}

type Types struct {
	Binary               bool     `protobuf:"varint,100,opt,name=binary,proto3" json:"binary,omitempty"`
	Set                  bool     `protobuf:"varint,200,opt,name=set,proto3" json:"set,omitempty"`
	UnixSecond           bool     `protobuf:"varint,300,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
	UnixMilli            bool     `protobuf:"varint,301,opt,name=unix_milli,json=unixMilli,proto3" json:"unix_milli,omitempty"`
	UnixNano             bool     `protobuf:"varint,302,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Types) Reset()         { *m = Types{} }
func (m *Types) String() string { return proto.CompactTextString(m) }
func (*Types) ProtoMessage()    {}
func (*Types) Descriptor() ([]byte, []int) {
	return fileDescriptor_67582952f82a4846, []int{3}
}

func (m *Types) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Types.Unmarshal(m, b)
}
func (m *Types) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Types.Marshal(b, m, deterministic)
}
func (m *Types) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Types.Merge(m, src)
}
func (m *Types) XXX_Size() int {
	return xxx_messageInfo_Types.Size(m)
}
func (m *Types) XXX_DiscardUnknown() {
	xxx_messageInfo_Types.DiscardUnknown(m)
}

var xxx_messageInfo_Types proto.InternalMessageInfo

func (m *Types) GetBinary() bool {
	if m != nil {
		return m.Binary
	}
	return false
}

func (m *Types) GetSet() bool {
	if m != nil {
		return m.Set
	}
	return false
}

func (m *Types) GetUnixSecond() bool {
	if m != nil {
		return m.UnixSecond
	}
	return false
}

func (m *Types) GetUnixMilli() bool {
	if m != nil {
		return m.UnixMilli
	}
	return false
}

func (m *Types) GetUnixNano() bool {
	if m != nil {
		return m.UnixNano
	}
	return false
}

var E_Msg = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.MessageOptions)(nil),
	ExtensionType: (*DynamoMessageOptions)(nil),
	Field:         6000,
	Name:          "dynamo.msg",
	Tag:           "bytes,6000,opt,name=msg",
	Filename:      "dynamo.proto",
}

var E_Field = &proto.ExtensionDesc{
	ExtendedType:  (*descriptor.FieldOptions)(nil),
	ExtensionType: (*DynamoFieldOptions)(nil),
	Field:         6000,
	Name:          "dynamo.field",
	Tag:           "bytes,6000,opt,name=field",
	Filename:      "dynamo.proto",
}

func init() {
	proto.RegisterType((*DynamoMessageOptions)(nil), "dynamo.DynamoMessageOptions")
	proto.RegisterType((*Key)(nil), "dynamo.Key")
	proto.RegisterType((*DynamoFieldOptions)(nil), "dynamo.DynamoFieldOptions")
	proto.RegisterType((*Types)(nil), "dynamo.Types")
	proto.RegisterExtension(E_Msg)
	proto.RegisterExtension(E_Field)
}

func init() {
	proto.RegisterFile("dynamo.proto", fileDescriptor_67582952f82a4846)
}

var fileDescriptor_67582952f82a4846 = []byte{
	// 455 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0xd6, 0x6e, 0xd2, 0xd5, 0x66, 0x96, 0x22, 0x61, 0x21, 0x64, 0xad, 0x0a, 0x0d, 0x7b, 0x5a,
	0x84, 0x36, 0x2b, 0x95, 0x5b, 0x8f, 0x08, 0x71, 0xa9, 0x0a, 0x55, 0xe0, 0xc4, 0x65, 0xe5, 0x24,
	0xde, 0x60, 0x91, 0xd8, 0xc6, 0x76, 0xa4, 0xe6, 0x35, 0x78, 0x0e, 0xe0, 0xc0, 0x53, 0xf0, 0x38,
	0x3c, 0x02, 0xf2, 0x38, 0x69, 0xb7, 0x94, 0x53, 0xe6, 0xfb, 0xd1, 0xe7, 0x99, 0xc9, 0xc0, 0x83,
	0xaa, 0x97, 0xac, 0x55, 0x99, 0x36, 0xca, 0x29, 0x32, 0x0b, 0x68, 0x99, 0xd6, 0x4a, 0xd5, 0x0d,
	0xdf, 0x22, 0x5b, 0x74, 0xfb, 0x6d, 0xc5, 0x6d, 0x69, 0x84, 0x76, 0xca, 0x04, 0xe7, 0xea, 0xd7,
	0x04, 0x1e, 0xbf, 0x41, 0xf3, 0x25, 0xb7, 0x96, 0xd5, 0xfc, 0xbd, 0x76, 0x42, 0x49, 0x4b, 0x96,
	0x30, 0xaf, 0x84, 0x65, 0x45, 0xc3, 0x2b, 0x3a, 0x49, 0x27, 0xeb, 0x79, 0x7e, 0x83, 0xc9, 0x0b,
	0x48, 0x34, 0x33, 0x4e, 0x78, 0x27, 0x9d, 0xa6, 0x93, 0xf5, 0xe2, 0x6c, 0x91, 0x0d, 0x0d, 0x5c,
	0xf0, 0x3e, 0xbf, 0x55, 0xc9, 0x29, 0xc4, 0x56, 0x19, 0x47, 0xa3, 0xfb, 0x2e, 0x14, 0xc8, 0x19,
	0x3c, 0x2c, 0x55, 0xab, 0x55, 0x27, 0xab, 0xdd, 0x5e, 0xf0, 0xa6, 0xa2, 0x71, 0x1a, 0xfd, 0x6b,
	0x3d, 0x1e, 0x2d, 0x6f, 0xbd, 0x63, 0x55, 0x43, 0x74, 0xc1, 0x7b, 0x42, 0x20, 0x96, 0xac, 0xe5,
	0xd8, 0x5e, 0x92, 0x63, 0x4d, 0x9e, 0xc0, 0x0c, 0x53, 0x2c, 0x9d, 0xa6, 0xd1, 0x3a, 0xc9, 0x07,
	0xe4, 0x79, 0x6d, 0xf8, 0x5e, 0x5c, 0x63, 0x27, 0x49, 0x3e, 0x20, 0x72, 0x02, 0x89, 0xe5, 0x9a,
	0x19, 0xe6, 0x94, 0xa1, 0x31, 0x4a, 0xb7, 0xc4, 0x6a, 0x07, 0x24, 0x2c, 0x07, 0xdf, 0x1d, 0x57,
	0x43, 0x20, 0xb6, 0x5f, 0x84, 0x1e, 0xd6, 0x82, 0xf5, 0x4d, 0x2f, 0xd3, 0x83, 0x5e, 0x9e, 0x43,
	0xec, 0x7a, 0xcd, 0x87, 0xd9, 0x8f, 0xc7, 0x81, 0x3e, 0xf6, 0x9a, 0xdb, 0x1c, 0xa5, 0xd5, 0xb7,
	0x09, 0x1c, 0x21, 0xf6, 0x0d, 0x16, 0x42, 0x32, 0xd3, 0xd3, 0x0a, 0x63, 0x07, 0x44, 0x1e, 0x41,
	0x64, 0xb9, 0xa3, 0xbf, 0xc3, 0x63, 0xbe, 0x26, 0x29, 0x2c, 0x3a, 0x29, 0xae, 0x77, 0x96, 0x97,
	0x4a, 0x56, 0xf4, 0xfb, 0x14, 0x25, 0xf0, 0xdc, 0x07, 0xa4, 0xc8, 0x33, 0x40, 0xb4, 0x6b, 0x45,
	0xd3, 0x08, 0xfa, 0x23, 0x18, 0x12, 0x4f, 0x5d, 0x7a, 0xc6, 0x4f, 0x8d, 0xba, 0x64, 0x52, 0xd1,
	0x9f, 0x41, 0x9e, 0x7b, 0xe6, 0x1d, 0x93, 0xea, 0xfc, 0x0a, 0xa2, 0xd6, 0xd6, 0xe4, 0x34, 0x0b,
	0xd7, 0x93, 0x8d, 0xd7, 0x93, 0xdd, 0x3d, 0x11, 0xfa, 0x27, 0xc3, 0xc1, 0x4e, 0xc6, 0xc1, 0xfe,
	0x77, 0x47, 0xb9, 0x8f, 0x3a, 0xbf, 0x82, 0x23, 0xfc, 0x0f, 0xe4, 0xe9, 0xbd, 0xcc, 0xc3, 0xcd,
	0x8e, 0x89, 0xcb, 0xbb, 0x89, 0x87, 0x96, 0x3c, 0x04, 0xbd, 0xde, 0x7c, 0x7a, 0x59, 0x0b, 0xf7,
	0xb9, 0x2b, 0xb2, 0x52, 0xb5, 0x5b, 0xfd, 0xb5, 0xe3, 0x46, 0xb2, 0x70, 0xe7, 0xe5, 0xa6, 0xe6,
	0x72, 0x13, 0x12, 0xb6, 0xe1, 0x53, 0xcc, 0x50, 0x79, 0xf5, 0x37, 0x00, 0x00, 0xff, 0xff, 0x1c,
	0xbc, 0x2d, 0x64, 0x27, 0x03, 0x00, 0x00,
}
