// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.5
// source: dynamo/v1/dynamo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamoMessageOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Disables generation for this message
	Disabled bool `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// A compound value that can be used as a partition and sort key. Multiple
	// keys will be added as gsi keys after the first.
	Key []*Key `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
}

func (x *DynamoMessageOptions) Reset() {
	*x = DynamoMessageOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamo_v1_dynamo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamoMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoMessageOptions) ProtoMessage() {}

func (x *DynamoMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoMessageOptions.ProtoReflect.Descriptor instead.
func (*DynamoMessageOptions) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{0}
}

func (x *DynamoMessageOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DynamoMessageOptions) GetKey() []*Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type Key struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PkFields []string `protobuf:"bytes,1,rep,name=pk_fields,json=pkFields,proto3" json:"pk_fields,omitempty"`
	SkFields []string `protobuf:"bytes,2,rep,name=sk_fields,json=skFields,proto3" json:"sk_fields,omitempty"`
	// If set, the value of sort key is set to a constant string.  In this case
	// sk_fields is ignored.
	SkConst string `protobuf:"bytes,3,opt,name=sk_const,json=skConst,proto3" json:"sk_const,omitempty"`
}

func (x *Key) Reset() {
	*x = Key{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamo_v1_dynamo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetPkFields() []string {
	if x != nil {
		return x.PkFields
	}
	return nil
}

func (x *Key) GetSkFields() []string {
	if x != nil {
		return x.SkFields
	}
	return nil
}

func (x *Key) GetSkConst() string {
	if x != nil {
		return x.SkConst
	}
	return ""
}

type DynamoFieldOptions struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Expose bool   `protobuf:"varint,1,opt,name=expose,proto3" json:"expose,omitempty"`
	Name   string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type   *Types `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *DynamoFieldOptions) Reset() {
	*x = DynamoFieldOptions{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamo_v1_dynamo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DynamoFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoFieldOptions) ProtoMessage() {}

func (x *DynamoFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoFieldOptions.ProtoReflect.Descriptor instead.
func (*DynamoFieldOptions) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{2}
}

func (x *DynamoFieldOptions) GetExpose() bool {
	if x != nil {
		return x.Expose
	}
	return false
}

func (x *DynamoFieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DynamoFieldOptions) GetType() *Types {
	if x != nil {
		return x.Type
	}
	return nil
}

type Types struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set        bool `protobuf:"varint,200,opt,name=set,proto3" json:"set,omitempty"`
	UnixSecond bool `protobuf:"varint,300,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
	UnixMilli  bool `protobuf:"varint,301,opt,name=unix_milli,json=unixMilli,proto3" json:"unix_milli,omitempty"`
	UnixNano   bool `protobuf:"varint,302,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
}

func (x *Types) Reset() {
	*x = Types{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynamo_v1_dynamo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{3}
}

func (x *Types) GetSet() bool {
	if x != nil {
		return x.Set
	}
	return false
}

func (x *Types) GetUnixSecond() bool {
	if x != nil {
		return x.UnixSecond
	}
	return false
}

func (x *Types) GetUnixMilli() bool {
	if x != nil {
		return x.UnixMilli
	}
	return false
}

func (x *Types) GetUnixNano() bool {
	if x != nil {
		return x.UnixNano
	}
	return false
}

var file_dynamo_v1_dynamo_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*DynamoMessageOptions)(nil),
		Field:         6000,
		Name:          "dynamo.v1.msg",
		Tag:           "bytes,6000,opt,name=msg",
		Filename:      "dynamo/v1/dynamo.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DynamoFieldOptions)(nil),
		Field:         6000,
		Name:          "dynamo.v1.field",
		Tag:           "bytes,6000,opt,name=field",
		Filename:      "dynamo/v1/dynamo.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional dynamo.v1.DynamoMessageOptions msg = 6000;
	E_Msg = &file_dynamo_v1_dynamo_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional dynamo.v1.DynamoFieldOptions field = 6000;
	E_Field = &file_dynamo_v1_dynamo_proto_extTypes[1]
)

var File_dynamo_v1_dynamo_proto protoreflect.FileDescriptor

var file_dynamo_v1_dynamo_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x79, 0x6e, 0x61,
	0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f,
	0x2e, 0x76, 0x31, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x54, 0x0a, 0x14, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1a, 0x0a,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x08, 0x64, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x20, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x65, 0x79, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x5a, 0x0a, 0x03, 0x4b,
	0x65, 0x79, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x6b, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x70, 0x6b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x5f, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x6b, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x73, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x6b, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x73, 0x6b, 0x43, 0x6f, 0x6e, 0x73, 0x74, 0x22, 0x66, 0x0a, 0x12, 0x44, 0x79, 0x6e, 0x61, 0x6d,
	0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x78, 0x70, 0x6f, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x78, 0x70, 0x6f, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x24, 0x0a, 0x04, 0x74, 0x79, 0x70,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f,
	0x2e, 0x76, 0x31, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x73, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x22,
	0x7a, 0x0a, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x11, 0x0a, 0x03, 0x73, 0x65, 0x74, 0x18,
	0xc8, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x75,
	0x6e, 0x69, 0x78, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x18, 0xac, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x75, 0x6e, 0x69, 0x78, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x69, 0x6c, 0x6c, 0x69, 0x18, 0xad, 0x02, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x09, 0x75, 0x6e, 0x69, 0x78, 0x4d, 0x69, 0x6c, 0x6c, 0x69, 0x12, 0x1c, 0x0a,
	0x09, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x18, 0xae, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x78, 0x4e, 0x61, 0x6e, 0x6f, 0x3a, 0x53, 0x0a, 0x03, 0x6d,
	0x73, 0x67, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0xf0, 0x2e, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x64, 0x79, 0x6e,
	0x61, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x03, 0x6d, 0x73, 0x67,
	0x3a, 0x53, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x1d, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x46, 0x69, 0x65, 0x6c,
	0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xf0, 0x2e, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1d, 0x2e, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x79, 0x6e, 0x61,
	0x6d, 0x6f, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x4f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x52, 0x05,
	0x66, 0x69, 0x65, 0x6c, 0x64, 0x42, 0x30, 0x5a, 0x2e, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x70, 0x71, 0x75, 0x65, 0x72, 0x6e, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x63, 0x2d, 0x67, 0x65, 0x6e, 0x2d, 0x64, 0x79, 0x6e, 0x61, 0x6d, 0x6f, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x6d, 0x6f, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynamo_v1_dynamo_proto_rawDescOnce sync.Once
	file_dynamo_v1_dynamo_proto_rawDescData = file_dynamo_v1_dynamo_proto_rawDesc
)

func file_dynamo_v1_dynamo_proto_rawDescGZIP() []byte {
	file_dynamo_v1_dynamo_proto_rawDescOnce.Do(func() {
		file_dynamo_v1_dynamo_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynamo_v1_dynamo_proto_rawDescData)
	})
	return file_dynamo_v1_dynamo_proto_rawDescData
}

var file_dynamo_v1_dynamo_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_dynamo_v1_dynamo_proto_goTypes = []interface{}{
	(*DynamoMessageOptions)(nil),        // 0: dynamo.v1.DynamoMessageOptions
	(*Key)(nil),                         // 1: dynamo.v1.Key
	(*DynamoFieldOptions)(nil),          // 2: dynamo.v1.DynamoFieldOptions
	(*Types)(nil),                       // 3: dynamo.v1.Types
	(*descriptorpb.MessageOptions)(nil), // 4: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 5: google.protobuf.FieldOptions
}
var file_dynamo_v1_dynamo_proto_depIdxs = []int32{
	1, // 0: dynamo.v1.DynamoMessageOptions.key:type_name -> dynamo.v1.Key
	3, // 1: dynamo.v1.DynamoFieldOptions.type:type_name -> dynamo.v1.Types
	4, // 2: dynamo.v1.msg:extendee -> google.protobuf.MessageOptions
	5, // 3: dynamo.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 4: dynamo.v1.msg:type_name -> dynamo.v1.DynamoMessageOptions
	2, // 5: dynamo.v1.field:type_name -> dynamo.v1.DynamoFieldOptions
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	4, // [4:6] is the sub-list for extension type_name
	2, // [2:4] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_dynamo_v1_dynamo_proto_init() }
func file_dynamo_v1_dynamo_proto_init() {
	if File_dynamo_v1_dynamo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynamo_v1_dynamo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamoMessageOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamo_v1_dynamo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Key); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamo_v1_dynamo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DynamoFieldOptions); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_dynamo_v1_dynamo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Types); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynamo_v1_dynamo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_dynamo_v1_dynamo_proto_goTypes,
		DependencyIndexes: file_dynamo_v1_dynamo_proto_depIdxs,
		MessageInfos:      file_dynamo_v1_dynamo_proto_msgTypes,
		ExtensionInfos:    file_dynamo_v1_dynamo_proto_extTypes,
	}.Build()
	File_dynamo_v1_dynamo_proto = out.File
	file_dynamo_v1_dynamo_proto_rawDesc = nil
	file_dynamo_v1_dynamo_proto_goTypes = nil
	file_dynamo_v1_dynamo_proto_depIdxs = nil
}
