// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: dynamo/v1/dynamo.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DynamoMessageOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Disables generation for this message
	Disabled bool `protobuf:"varint,1,opt,name=disabled,proto3" json:"disabled,omitempty"`
	// A compound value that can be used as a partition and sort key. Multiple
	// keys will be added as gsi keys after the first.
	Key           []*Key `protobuf:"bytes,2,rep,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoMessageOptions) Reset() {
	*x = DynamoMessageOptions{}
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoMessageOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoMessageOptions) ProtoMessage() {}

func (x *DynamoMessageOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoMessageOptions.ProtoReflect.Descriptor instead.
func (*DynamoMessageOptions) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{0}
}

func (x *DynamoMessageOptions) GetDisabled() bool {
	if x != nil {
		return x.Disabled
	}
	return false
}

func (x *DynamoMessageOptions) GetKey() []*Key {
	if x != nil {
		return x.Key
	}
	return nil
}

type Key struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PkFields []string               `protobuf:"bytes,1,rep,name=pk_fields,json=pkFields,proto3" json:"pk_fields,omitempty"`
	SkFields []string               `protobuf:"bytes,2,rep,name=sk_fields,json=skFields,proto3" json:"sk_fields,omitempty"`
	// If set, the value of sort key is set to a constant string.  In this case
	// sk_fields is ignored.
	SkConst       string        `protobuf:"bytes,3,opt,name=sk_const,json=skConst,proto3" json:"sk_const,omitempty"`
	Shard         *ShardOptions `protobuf:"bytes,4,opt,name=shard,proto3" json:"shard,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Key) Reset() {
	*x = Key{}
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Key) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Key) ProtoMessage() {}

func (x *Key) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Key.ProtoReflect.Descriptor instead.
func (*Key) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{1}
}

func (x *Key) GetPkFields() []string {
	if x != nil {
		return x.PkFields
	}
	return nil
}

func (x *Key) GetSkFields() []string {
	if x != nil {
		return x.SkFields
	}
	return nil
}

func (x *Key) GetSkConst() string {
	if x != nil {
		return x.SkConst
	}
	return ""
}

func (x *Key) GetShard() *ShardOptions {
	if x != nil {
		return x.Shard
	}
	return nil
}

type ShardOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Sharding is opt-in
	Enabled       bool   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ShardCount    uint32 `protobuf:"varint,2,opt,name=shard_count,json=shardCount,proto3" json:"shard_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShardOptions) Reset() {
	*x = ShardOptions{}
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShardOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShardOptions) ProtoMessage() {}

func (x *ShardOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShardOptions.ProtoReflect.Descriptor instead.
func (*ShardOptions) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{2}
}

func (x *ShardOptions) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ShardOptions) GetShardCount() uint32 {
	if x != nil {
		return x.ShardCount
	}
	return 0
}

type DynamoFieldOptions struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Expose        bool                   `protobuf:"varint,1,opt,name=expose,proto3" json:"expose,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type          *Types                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DynamoFieldOptions) Reset() {
	*x = DynamoFieldOptions{}
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DynamoFieldOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DynamoFieldOptions) ProtoMessage() {}

func (x *DynamoFieldOptions) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DynamoFieldOptions.ProtoReflect.Descriptor instead.
func (*DynamoFieldOptions) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{3}
}

func (x *DynamoFieldOptions) GetExpose() bool {
	if x != nil {
		return x.Expose
	}
	return false
}

func (x *DynamoFieldOptions) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DynamoFieldOptions) GetType() *Types {
	if x != nil {
		return x.Type
	}
	return nil
}

type Types struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Set           bool                   `protobuf:"varint,200,opt,name=set,proto3" json:"set,omitempty"`
	UnixSecond    bool                   `protobuf:"varint,300,opt,name=unix_second,json=unixSecond,proto3" json:"unix_second,omitempty"`
	UnixMilli     bool                   `protobuf:"varint,301,opt,name=unix_milli,json=unixMilli,proto3" json:"unix_milli,omitempty"`
	UnixNano      bool                   `protobuf:"varint,302,opt,name=unix_nano,json=unixNano,proto3" json:"unix_nano,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Types) Reset() {
	*x = Types{}
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Types) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Types) ProtoMessage() {}

func (x *Types) ProtoReflect() protoreflect.Message {
	mi := &file_dynamo_v1_dynamo_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Types.ProtoReflect.Descriptor instead.
func (*Types) Descriptor() ([]byte, []int) {
	return file_dynamo_v1_dynamo_proto_rawDescGZIP(), []int{4}
}

func (x *Types) GetSet() bool {
	if x != nil {
		return x.Set
	}
	return false
}

func (x *Types) GetUnixSecond() bool {
	if x != nil {
		return x.UnixSecond
	}
	return false
}

func (x *Types) GetUnixMilli() bool {
	if x != nil {
		return x.UnixMilli
	}
	return false
}

func (x *Types) GetUnixNano() bool {
	if x != nil {
		return x.UnixNano
	}
	return false
}

var file_dynamo_v1_dynamo_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MessageOptions)(nil),
		ExtensionType: (*DynamoMessageOptions)(nil),
		Field:         6000,
		Name:          "dynamo.v1.msg",
		Tag:           "bytes,6000,opt,name=msg",
		Filename:      "dynamo/v1/dynamo.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*DynamoFieldOptions)(nil),
		Field:         6000,
		Name:          "dynamo.v1.field",
		Tag:           "bytes,6000,opt,name=field",
		Filename:      "dynamo/v1/dynamo.proto",
	},
}

// Extension fields to descriptorpb.MessageOptions.
var (
	// optional dynamo.v1.DynamoMessageOptions msg = 6000;
	E_Msg = &file_dynamo_v1_dynamo_proto_extTypes[0]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional dynamo.v1.DynamoFieldOptions field = 6000;
	E_Field = &file_dynamo_v1_dynamo_proto_extTypes[1]
)

var File_dynamo_v1_dynamo_proto protoreflect.FileDescriptor

const file_dynamo_v1_dynamo_proto_rawDesc = "" +
	"\n" +
	"\x16dynamo/v1/dynamo.proto\x12\tdynamo.v1\x1a google/protobuf/descriptor.proto\"T\n" +
	"\x14DynamoMessageOptions\x12\x1a\n" +
	"\bdisabled\x18\x01 \x01(\bR\bdisabled\x12 \n" +
	"\x03key\x18\x02 \x03(\v2\x0e.dynamo.v1.KeyR\x03key\"\x89\x01\n" +
	"\x03Key\x12\x1b\n" +
	"\tpk_fields\x18\x01 \x03(\tR\bpkFields\x12\x1b\n" +
	"\tsk_fields\x18\x02 \x03(\tR\bskFields\x12\x19\n" +
	"\bsk_const\x18\x03 \x01(\tR\askConst\x12-\n" +
	"\x05shard\x18\x04 \x01(\v2\x17.dynamo.v1.ShardOptionsR\x05shard\"I\n" +
	"\fShardOptions\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vshard_count\x18\x02 \x01(\rR\n" +
	"shardCount\"f\n" +
	"\x12DynamoFieldOptions\x12\x16\n" +
	"\x06expose\x18\x01 \x01(\bR\x06expose\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12$\n" +
	"\x04type\x18\x03 \x01(\v2\x10.dynamo.v1.TypesR\x04type\"z\n" +
	"\x05Types\x12\x11\n" +
	"\x03set\x18\xc8\x01 \x01(\bR\x03set\x12 \n" +
	"\vunix_second\x18\xac\x02 \x01(\bR\n" +
	"unixSecond\x12\x1e\n" +
	"\n" +
	"unix_milli\x18\xad\x02 \x01(\bR\tunixMilli\x12\x1c\n" +
	"\tunix_nano\x18\xae\x02 \x01(\bR\bunixNano:S\n" +
	"\x03msg\x12\x1f.google.protobuf.MessageOptions\x18\xf0. \x01(\v2\x1f.dynamo.v1.DynamoMessageOptionsR\x03msg:S\n" +
	"\x05field\x12\x1d.google.protobuf.FieldOptions\x18\xf0. \x01(\v2\x1d.dynamo.v1.DynamoFieldOptionsR\x05fieldB\x91\x01\n" +
	"\rcom.dynamo.v1B\vDynamoProtoP\x01Z.github.com/pquerna/protoc-gen-dynamo/dynamo/v1\xa2\x02\x03DXX\xaa\x02\tDynamo.V1\xca\x02\tDynamo\\V1\xe2\x02\x15Dynamo\\V1\\GPBMetadata\xea\x02\n" +
	"Dynamo::V1b\x06proto3"

var (
	file_dynamo_v1_dynamo_proto_rawDescOnce sync.Once
	file_dynamo_v1_dynamo_proto_rawDescData []byte
)

func file_dynamo_v1_dynamo_proto_rawDescGZIP() []byte {
	file_dynamo_v1_dynamo_proto_rawDescOnce.Do(func() {
		file_dynamo_v1_dynamo_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dynamo_v1_dynamo_proto_rawDesc), len(file_dynamo_v1_dynamo_proto_rawDesc)))
	})
	return file_dynamo_v1_dynamo_proto_rawDescData
}

var file_dynamo_v1_dynamo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_dynamo_v1_dynamo_proto_goTypes = []any{
	(*DynamoMessageOptions)(nil),        // 0: dynamo.v1.DynamoMessageOptions
	(*Key)(nil),                         // 1: dynamo.v1.Key
	(*ShardOptions)(nil),                // 2: dynamo.v1.ShardOptions
	(*DynamoFieldOptions)(nil),          // 3: dynamo.v1.DynamoFieldOptions
	(*Types)(nil),                       // 4: dynamo.v1.Types
	(*descriptorpb.MessageOptions)(nil), // 5: google.protobuf.MessageOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_dynamo_v1_dynamo_proto_depIdxs = []int32{
	1, // 0: dynamo.v1.DynamoMessageOptions.key:type_name -> dynamo.v1.Key
	2, // 1: dynamo.v1.Key.shard:type_name -> dynamo.v1.ShardOptions
	4, // 2: dynamo.v1.DynamoFieldOptions.type:type_name -> dynamo.v1.Types
	5, // 3: dynamo.v1.msg:extendee -> google.protobuf.MessageOptions
	6, // 4: dynamo.v1.field:extendee -> google.protobuf.FieldOptions
	0, // 5: dynamo.v1.msg:type_name -> dynamo.v1.DynamoMessageOptions
	3, // 6: dynamo.v1.field:type_name -> dynamo.v1.DynamoFieldOptions
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	5, // [5:7] is the sub-list for extension type_name
	3, // [3:5] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_dynamo_v1_dynamo_proto_init() }
func file_dynamo_v1_dynamo_proto_init() {
	if File_dynamo_v1_dynamo_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dynamo_v1_dynamo_proto_rawDesc), len(file_dynamo_v1_dynamo_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_dynamo_v1_dynamo_proto_goTypes,
		DependencyIndexes: file_dynamo_v1_dynamo_proto_depIdxs,
		MessageInfos:      file_dynamo_v1_dynamo_proto_msgTypes,
		ExtensionInfos:    file_dynamo_v1_dynamo_proto_extTypes,
	}.Build()
	File_dynamo_v1_dynamo_proto = out.File
	file_dynamo_v1_dynamo_proto_goTypes = nil
	file_dynamo_v1_dynamo_proto_depIdxs = nil
}
