// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        (unknown)
// source: v1/example.proto

package v1

import (
	_ "github.com/pquerna/protoc-gen-dynamo/dynamo/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/gofeaturespb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BasicEnum int32

const (
	BasicEnum_First  BasicEnum = 0
	BasicEnum_Second BasicEnum = 1
)

// Enum value maps for BasicEnum.
var (
	BasicEnum_name = map[int32]string{
		0: "First",
		1: "Second",
	}
	BasicEnum_value = map[string]int32{
		"First":  0,
		"Second": 1,
	}
)

func (x BasicEnum) Enum() *BasicEnum {
	p := new(BasicEnum)
	*p = x
	return p
}

func (x BasicEnum) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BasicEnum) Descriptor() protoreflect.EnumDescriptor {
	return file_v1_example_proto_enumTypes[0].Descriptor()
}

func (BasicEnum) Type() protoreflect.EnumType {
	return &file_v1_example_proto_enumTypes[0]
}

func (x BasicEnum) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

type Store struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Country         *string                `protobuf:"bytes,2,opt,name=country"`
	xxx_hidden_Region          *string                `protobuf:"bytes,3,opt,name=region"`
	xxx_hidden_State           *string                `protobuf:"bytes,4,opt,name=state"`
	xxx_hidden_City            *string                `protobuf:"bytes,5,opt,name=city"`
	xxx_hidden_Closed          bool                   `protobuf:"varint,6,opt,name=closed"`
	xxx_hidden_OpeningDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=opening_date,json=openingDate"`
	xxx_hidden_BestEmployeeIds []string               `protobuf:"bytes,8,rep,name=best_employee_ids,json=bestEmployeeIds"`
	xxx_hidden_BinDate         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=bin_date,json=binDate"`
	xxx_hidden_UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt"`
	xxx_hidden_ExpiresAtMs     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at_ms,json=expiresAtMs"`
	xxx_hidden_ExpiresAtNs     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at_ns,json=expiresAtNs"`
	xxx_hidden_Foo             uint64                 `protobuf:"varint,99,opt,name=foo"`
	xxx_hidden_Morefoo         []uint64               `protobuf:"varint,100,rep,packed,name=morefoo"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *Store) Reset() {
	*x = Store{}
	mi := &file_v1_example_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Store) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Store) ProtoMessage() {}

func (x *Store) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Store) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *Store) GetCountry() string {
	if x != nil {
		if x.xxx_hidden_Country != nil {
			return *x.xxx_hidden_Country
		}
		return ""
	}
	return ""
}

func (x *Store) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *Store) GetState() string {
	if x != nil {
		if x.xxx_hidden_State != nil {
			return *x.xxx_hidden_State
		}
		return ""
	}
	return ""
}

func (x *Store) GetCity() string {
	if x != nil {
		if x.xxx_hidden_City != nil {
			return *x.xxx_hidden_City
		}
		return ""
	}
	return ""
}

func (x *Store) GetClosed() bool {
	if x != nil {
		return x.xxx_hidden_Closed
	}
	return false
}

func (x *Store) GetOpeningDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_OpeningDate
	}
	return nil
}

func (x *Store) GetBestEmployeeIds() []string {
	if x != nil {
		return x.xxx_hidden_BestEmployeeIds
	}
	return nil
}

func (x *Store) GetBinDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_BinDate
	}
	return nil
}

func (x *Store) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *Store) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *Store) GetExpiresAtMs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAtMs
	}
	return nil
}

func (x *Store) GetExpiresAtNs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAtNs
	}
	return nil
}

func (x *Store) GetFoo() uint64 {
	if x != nil {
		return x.xxx_hidden_Foo
	}
	return 0
}

func (x *Store) GetMorefoo() []uint64 {
	if x != nil {
		return x.xxx_hidden_Morefoo
	}
	return nil
}

func (x *Store) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 15)
}

func (x *Store) SetCountry(v string) {
	x.xxx_hidden_Country = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 15)
}

func (x *Store) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 15)
}

func (x *Store) SetState(v string) {
	x.xxx_hidden_State = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 15)
}

func (x *Store) SetCity(v string) {
	x.xxx_hidden_City = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 15)
}

func (x *Store) SetClosed(v bool) {
	x.xxx_hidden_Closed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 15)
}

func (x *Store) SetOpeningDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_OpeningDate = v
}

func (x *Store) SetBestEmployeeIds(v []string) {
	x.xxx_hidden_BestEmployeeIds = v
}

func (x *Store) SetBinDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_BinDate = v
}

func (x *Store) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *Store) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *Store) SetExpiresAtMs(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAtMs = v
}

func (x *Store) SetExpiresAtNs(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAtNs = v
}

func (x *Store) SetFoo(v uint64) {
	x.xxx_hidden_Foo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 15)
}

func (x *Store) SetMorefoo(v []uint64) {
	x.xxx_hidden_Morefoo = v
}

func (x *Store) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Store) HasCountry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Store) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Store) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Store) HasCity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Store) HasClosed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *Store) HasOpeningDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OpeningDate != nil
}

func (x *Store) HasBinDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BinDate != nil
}

func (x *Store) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *Store) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *Store) HasExpiresAtMs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAtMs != nil
}

func (x *Store) HasExpiresAtNs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAtNs != nil
}

func (x *Store) HasFoo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *Store) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *Store) ClearCountry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Country = nil
}

func (x *Store) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Region = nil
}

func (x *Store) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = nil
}

func (x *Store) ClearCity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_City = nil
}

func (x *Store) ClearClosed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Closed = false
}

func (x *Store) ClearOpeningDate() {
	x.xxx_hidden_OpeningDate = nil
}

func (x *Store) ClearBinDate() {
	x.xxx_hidden_BinDate = nil
}

func (x *Store) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *Store) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

func (x *Store) ClearExpiresAtMs() {
	x.xxx_hidden_ExpiresAtMs = nil
}

func (x *Store) ClearExpiresAtNs() {
	x.xxx_hidden_ExpiresAtNs = nil
}

func (x *Store) ClearFoo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Foo = 0
}

type Store_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              *string
	Country         *string
	Region          *string
	State           *string
	City            *string
	Closed          *bool
	OpeningDate     *timestamppb.Timestamp
	BestEmployeeIds []string
	BinDate         *timestamppb.Timestamp
	UpdatedAt       *timestamppb.Timestamp
	ExpiresAt       *timestamppb.Timestamp
	ExpiresAtMs     *timestamppb.Timestamp
	ExpiresAtNs     *timestamppb.Timestamp
	Foo             *uint64
	Morefoo         []uint64
}

func (b0 Store_builder) Build() *Store {
	m0 := &Store{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 15)
		x.xxx_hidden_Id = b.Id
	}
	if b.Country != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 15)
		x.xxx_hidden_Country = b.Country
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 15)
		x.xxx_hidden_Region = b.Region
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 15)
		x.xxx_hidden_State = b.State
	}
	if b.City != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 15)
		x.xxx_hidden_City = b.City
	}
	if b.Closed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 15)
		x.xxx_hidden_Closed = *b.Closed
	}
	x.xxx_hidden_OpeningDate = b.OpeningDate
	x.xxx_hidden_BestEmployeeIds = b.BestEmployeeIds
	x.xxx_hidden_BinDate = b.BinDate
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_ExpiresAtMs = b.ExpiresAtMs
	x.xxx_hidden_ExpiresAtNs = b.ExpiresAtNs
	if b.Foo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 15)
		x.xxx_hidden_Foo = *b.Foo
	}
	x.xxx_hidden_Morefoo = b.Morefoo
	return m0
}

type User struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId    *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_DeletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt"`
	xxx_hidden_IdpId       *string                `protobuf:"bytes,6,opt,name=idp_id,json=idpId"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,7,opt,name=display_name,json=displayName"`
	xxx_hidden_Email       *string                `protobuf:"bytes,8,opt,name=email"`
	xxx_hidden_AnEnum      BasicEnum              `protobuf:"varint,9,opt,name=an_enum,json=anEnum,enum=examplepb.v1.BasicEnum"`
	xxx_hidden_ShardId     uint32                 `protobuf:"varint,10,opt,name=shard_id,json=shardId"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_v1_example_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *User) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *User) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *User) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *User) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *User) GetIdpId() string {
	if x != nil {
		if x.xxx_hidden_IdpId != nil {
			return *x.xxx_hidden_IdpId
		}
		return ""
	}
	return ""
}

func (x *User) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *User) GetAnEnum() BasicEnum {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 8) {
			return x.xxx_hidden_AnEnum
		}
	}
	return BasicEnum_First
}

func (x *User) GetShardId() uint32 {
	if x != nil {
		return x.xxx_hidden_ShardId
	}
	return 0
}

func (x *User) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 10)
}

func (x *User) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 10)
}

func (x *User) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *User) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *User) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *User) SetIdpId(v string) {
	x.xxx_hidden_IdpId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 10)
}

func (x *User) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 10)
}

func (x *User) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 10)
}

func (x *User) SetAnEnum(v BasicEnum) {
	x.xxx_hidden_AnEnum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 10)
}

func (x *User) SetShardId(v uint32) {
	x.xxx_hidden_ShardId = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 9, 10)
}

func (x *User) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *User) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *User) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *User) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *User) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *User) HasIdpId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *User) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *User) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *User) HasAnEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *User) HasShardId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 9)
}

func (x *User) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *User) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

func (x *User) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *User) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *User) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

func (x *User) ClearIdpId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IdpId = nil
}

func (x *User) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DisplayName = nil
}

func (x *User) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Email = nil
}

func (x *User) ClearAnEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_AnEnum = BasicEnum_First
}

func (x *User) ClearShardId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 9)
	x.xxx_hidden_ShardId = 0
}

type User_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId    *string
	Id          *string
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
	DeletedAt   *timestamppb.Timestamp
	IdpId       *string
	DisplayName *string
	Email       *string
	AnEnum      *BasicEnum
	ShardId     *uint32
}

func (b0 User_builder) Build() *User {
	m0 := &User{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 10)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 10)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DeletedAt = b.DeletedAt
	if b.IdpId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 10)
		x.xxx_hidden_IdpId = b.IdpId
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 10)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 10)
		x.xxx_hidden_Email = b.Email
	}
	if b.AnEnum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 10)
		x.xxx_hidden_AnEnum = *b.AnEnum
	}
	if b.ShardId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 9, 10)
		x.xxx_hidden_ShardId = *b.ShardId
	}
	return m0
}

type StoreV2 struct {
	state                      protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id              *string                `protobuf:"bytes,1,opt,name=id"`
	xxx_hidden_Country         *string                `protobuf:"bytes,2,opt,name=country"`
	xxx_hidden_Region          *string                `protobuf:"bytes,3,opt,name=region"`
	xxx_hidden_State           *string                `protobuf:"bytes,4,opt,name=state"`
	xxx_hidden_City            *string                `protobuf:"bytes,5,opt,name=city"`
	xxx_hidden_Closed          bool                   `protobuf:"varint,6,opt,name=closed"`
	xxx_hidden_OpeningDate     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=opening_date,json=openingDate"`
	xxx_hidden_BestEmployeeIds []string               `protobuf:"bytes,8,rep,name=best_employee_ids,json=bestEmployeeIds"`
	xxx_hidden_BinDate         *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=bin_date,json=binDate"`
	xxx_hidden_UpdatedAt       *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_ExpiresAt       *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=expires_at,json=expiresAt"`
	xxx_hidden_ExpiresAtMs     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=expires_at_ms,json=expiresAtMs"`
	xxx_hidden_ExpiresAtNs     *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=expires_at_ns,json=expiresAtNs"`
	xxx_hidden_Foo             uint64                 `protobuf:"varint,99,opt,name=foo"`
	xxx_hidden_Morefoo         []uint64               `protobuf:"varint,100,rep,packed,name=morefoo"`
	XXX_raceDetectHookData     protoimpl.RaceDetectHookData
	XXX_presence               [1]uint32
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *StoreV2) Reset() {
	*x = StoreV2{}
	mi := &file_v1_example_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreV2) ProtoMessage() {}

func (x *StoreV2) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *StoreV2) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *StoreV2) GetCountry() string {
	if x != nil {
		if x.xxx_hidden_Country != nil {
			return *x.xxx_hidden_Country
		}
		return ""
	}
	return ""
}

func (x *StoreV2) GetRegion() string {
	if x != nil {
		if x.xxx_hidden_Region != nil {
			return *x.xxx_hidden_Region
		}
		return ""
	}
	return ""
}

func (x *StoreV2) GetState() string {
	if x != nil {
		if x.xxx_hidden_State != nil {
			return *x.xxx_hidden_State
		}
		return ""
	}
	return ""
}

func (x *StoreV2) GetCity() string {
	if x != nil {
		if x.xxx_hidden_City != nil {
			return *x.xxx_hidden_City
		}
		return ""
	}
	return ""
}

func (x *StoreV2) GetClosed() bool {
	if x != nil {
		return x.xxx_hidden_Closed
	}
	return false
}

func (x *StoreV2) GetOpeningDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_OpeningDate
	}
	return nil
}

func (x *StoreV2) GetBestEmployeeIds() []string {
	if x != nil {
		return x.xxx_hidden_BestEmployeeIds
	}
	return nil
}

func (x *StoreV2) GetBinDate() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_BinDate
	}
	return nil
}

func (x *StoreV2) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *StoreV2) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAt
	}
	return nil
}

func (x *StoreV2) GetExpiresAtMs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAtMs
	}
	return nil
}

func (x *StoreV2) GetExpiresAtNs() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ExpiresAtNs
	}
	return nil
}

func (x *StoreV2) GetFoo() uint64 {
	if x != nil {
		return x.xxx_hidden_Foo
	}
	return 0
}

func (x *StoreV2) GetMorefoo() []uint64 {
	if x != nil {
		return x.xxx_hidden_Morefoo
	}
	return nil
}

func (x *StoreV2) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 15)
}

func (x *StoreV2) SetCountry(v string) {
	x.xxx_hidden_Country = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 15)
}

func (x *StoreV2) SetRegion(v string) {
	x.xxx_hidden_Region = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 15)
}

func (x *StoreV2) SetState(v string) {
	x.xxx_hidden_State = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 15)
}

func (x *StoreV2) SetCity(v string) {
	x.xxx_hidden_City = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 15)
}

func (x *StoreV2) SetClosed(v bool) {
	x.xxx_hidden_Closed = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 15)
}

func (x *StoreV2) SetOpeningDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_OpeningDate = v
}

func (x *StoreV2) SetBestEmployeeIds(v []string) {
	x.xxx_hidden_BestEmployeeIds = v
}

func (x *StoreV2) SetBinDate(v *timestamppb.Timestamp) {
	x.xxx_hidden_BinDate = v
}

func (x *StoreV2) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *StoreV2) SetExpiresAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAt = v
}

func (x *StoreV2) SetExpiresAtMs(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAtMs = v
}

func (x *StoreV2) SetExpiresAtNs(v *timestamppb.Timestamp) {
	x.xxx_hidden_ExpiresAtNs = v
}

func (x *StoreV2) SetFoo(v uint64) {
	x.xxx_hidden_Foo = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 13, 15)
}

func (x *StoreV2) SetMorefoo(v []uint64) {
	x.xxx_hidden_Morefoo = v
}

func (x *StoreV2) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *StoreV2) HasCountry() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *StoreV2) HasRegion() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *StoreV2) HasState() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *StoreV2) HasCity() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *StoreV2) HasClosed() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *StoreV2) HasOpeningDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_OpeningDate != nil
}

func (x *StoreV2) HasBinDate() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_BinDate != nil
}

func (x *StoreV2) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *StoreV2) HasExpiresAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAt != nil
}

func (x *StoreV2) HasExpiresAtMs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAtMs != nil
}

func (x *StoreV2) HasExpiresAtNs() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ExpiresAtNs != nil
}

func (x *StoreV2) HasFoo() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 13)
}

func (x *StoreV2) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = nil
}

func (x *StoreV2) ClearCountry() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Country = nil
}

func (x *StoreV2) ClearRegion() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Region = nil
}

func (x *StoreV2) ClearState() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_State = nil
}

func (x *StoreV2) ClearCity() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_City = nil
}

func (x *StoreV2) ClearClosed() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_Closed = false
}

func (x *StoreV2) ClearOpeningDate() {
	x.xxx_hidden_OpeningDate = nil
}

func (x *StoreV2) ClearBinDate() {
	x.xxx_hidden_BinDate = nil
}

func (x *StoreV2) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *StoreV2) ClearExpiresAt() {
	x.xxx_hidden_ExpiresAt = nil
}

func (x *StoreV2) ClearExpiresAtMs() {
	x.xxx_hidden_ExpiresAtMs = nil
}

func (x *StoreV2) ClearExpiresAtNs() {
	x.xxx_hidden_ExpiresAtNs = nil
}

func (x *StoreV2) ClearFoo() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 13)
	x.xxx_hidden_Foo = 0
}

type StoreV2_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id              *string
	Country         *string
	Region          *string
	State           *string
	City            *string
	Closed          *bool
	OpeningDate     *timestamppb.Timestamp
	BestEmployeeIds []string
	BinDate         *timestamppb.Timestamp
	UpdatedAt       *timestamppb.Timestamp
	ExpiresAt       *timestamppb.Timestamp
	ExpiresAtMs     *timestamppb.Timestamp
	ExpiresAtNs     *timestamppb.Timestamp
	Foo             *uint64
	Morefoo         []uint64
}

func (b0 StoreV2_builder) Build() *StoreV2 {
	m0 := &StoreV2{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 15)
		x.xxx_hidden_Id = b.Id
	}
	if b.Country != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 15)
		x.xxx_hidden_Country = b.Country
	}
	if b.Region != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 15)
		x.xxx_hidden_Region = b.Region
	}
	if b.State != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 15)
		x.xxx_hidden_State = b.State
	}
	if b.City != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 15)
		x.xxx_hidden_City = b.City
	}
	if b.Closed != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 15)
		x.xxx_hidden_Closed = *b.Closed
	}
	x.xxx_hidden_OpeningDate = b.OpeningDate
	x.xxx_hidden_BestEmployeeIds = b.BestEmployeeIds
	x.xxx_hidden_BinDate = b.BinDate
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_ExpiresAt = b.ExpiresAt
	x.xxx_hidden_ExpiresAtMs = b.ExpiresAtMs
	x.xxx_hidden_ExpiresAtNs = b.ExpiresAtNs
	if b.Foo != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 13, 15)
		x.xxx_hidden_Foo = *b.Foo
	}
	x.xxx_hidden_Morefoo = b.Morefoo
	return m0
}

type UserV2 struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_TenantId    *string                `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId"`
	xxx_hidden_Id          *string                `protobuf:"bytes,2,opt,name=id"`
	xxx_hidden_CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt"`
	xxx_hidden_UpdatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt"`
	xxx_hidden_DeletedAt   *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=deleted_at,json=deletedAt"`
	xxx_hidden_IdpId       *string                `protobuf:"bytes,6,opt,name=idp_id,json=idpId"`
	xxx_hidden_DisplayName *string                `protobuf:"bytes,7,opt,name=display_name,json=displayName"`
	xxx_hidden_Email       *string                `protobuf:"bytes,8,opt,name=email"`
	xxx_hidden_AnEnum      BasicEnum              `protobuf:"varint,9,opt,name=an_enum,json=anEnum,enum=examplepb.v1.BasicEnum"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *UserV2) Reset() {
	*x = UserV2{}
	mi := &file_v1_example_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserV2) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserV2) ProtoMessage() {}

func (x *UserV2) ProtoReflect() protoreflect.Message {
	mi := &file_v1_example_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *UserV2) GetTenantId() string {
	if x != nil {
		if x.xxx_hidden_TenantId != nil {
			return *x.xxx_hidden_TenantId
		}
		return ""
	}
	return ""
}

func (x *UserV2) GetId() string {
	if x != nil {
		if x.xxx_hidden_Id != nil {
			return *x.xxx_hidden_Id
		}
		return ""
	}
	return ""
}

func (x *UserV2) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_CreatedAt
	}
	return nil
}

func (x *UserV2) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_UpdatedAt
	}
	return nil
}

func (x *UserV2) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_DeletedAt
	}
	return nil
}

func (x *UserV2) GetIdpId() string {
	if x != nil {
		if x.xxx_hidden_IdpId != nil {
			return *x.xxx_hidden_IdpId
		}
		return ""
	}
	return ""
}

func (x *UserV2) GetDisplayName() string {
	if x != nil {
		if x.xxx_hidden_DisplayName != nil {
			return *x.xxx_hidden_DisplayName
		}
		return ""
	}
	return ""
}

func (x *UserV2) GetEmail() string {
	if x != nil {
		if x.xxx_hidden_Email != nil {
			return *x.xxx_hidden_Email
		}
		return ""
	}
	return ""
}

func (x *UserV2) GetAnEnum() BasicEnum {
	if x != nil {
		if protoimpl.X.Present(&(x.XXX_presence[0]), 8) {
			return x.xxx_hidden_AnEnum
		}
	}
	return BasicEnum_First
}

func (x *UserV2) SetTenantId(v string) {
	x.xxx_hidden_TenantId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 9)
}

func (x *UserV2) SetId(v string) {
	x.xxx_hidden_Id = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 9)
}

func (x *UserV2) SetCreatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_CreatedAt = v
}

func (x *UserV2) SetUpdatedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_UpdatedAt = v
}

func (x *UserV2) SetDeletedAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_DeletedAt = v
}

func (x *UserV2) SetIdpId(v string) {
	x.xxx_hidden_IdpId = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 5, 9)
}

func (x *UserV2) SetDisplayName(v string) {
	x.xxx_hidden_DisplayName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 6, 9)
}

func (x *UserV2) SetEmail(v string) {
	x.xxx_hidden_Email = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 7, 9)
}

func (x *UserV2) SetAnEnum(v BasicEnum) {
	x.xxx_hidden_AnEnum = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 8, 9)
}

func (x *UserV2) HasTenantId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *UserV2) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *UserV2) HasCreatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_CreatedAt != nil
}

func (x *UserV2) HasUpdatedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_UpdatedAt != nil
}

func (x *UserV2) HasDeletedAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_DeletedAt != nil
}

func (x *UserV2) HasIdpId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 5)
}

func (x *UserV2) HasDisplayName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 6)
}

func (x *UserV2) HasEmail() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 7)
}

func (x *UserV2) HasAnEnum() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 8)
}

func (x *UserV2) ClearTenantId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_TenantId = nil
}

func (x *UserV2) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Id = nil
}

func (x *UserV2) ClearCreatedAt() {
	x.xxx_hidden_CreatedAt = nil
}

func (x *UserV2) ClearUpdatedAt() {
	x.xxx_hidden_UpdatedAt = nil
}

func (x *UserV2) ClearDeletedAt() {
	x.xxx_hidden_DeletedAt = nil
}

func (x *UserV2) ClearIdpId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 5)
	x.xxx_hidden_IdpId = nil
}

func (x *UserV2) ClearDisplayName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 6)
	x.xxx_hidden_DisplayName = nil
}

func (x *UserV2) ClearEmail() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 7)
	x.xxx_hidden_Email = nil
}

func (x *UserV2) ClearAnEnum() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 8)
	x.xxx_hidden_AnEnum = BasicEnum_First
}

type UserV2_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	TenantId    *string
	Id          *string
	CreatedAt   *timestamppb.Timestamp
	UpdatedAt   *timestamppb.Timestamp
	DeletedAt   *timestamppb.Timestamp
	IdpId       *string
	DisplayName *string
	Email       *string
	AnEnum      *BasicEnum
}

func (b0 UserV2_builder) Build() *UserV2 {
	m0 := &UserV2{}
	b, x := &b0, m0
	_, _ = b, x
	if b.TenantId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 9)
		x.xxx_hidden_TenantId = b.TenantId
	}
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 9)
		x.xxx_hidden_Id = b.Id
	}
	x.xxx_hidden_CreatedAt = b.CreatedAt
	x.xxx_hidden_UpdatedAt = b.UpdatedAt
	x.xxx_hidden_DeletedAt = b.DeletedAt
	if b.IdpId != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 5, 9)
		x.xxx_hidden_IdpId = b.IdpId
	}
	if b.DisplayName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 6, 9)
		x.xxx_hidden_DisplayName = b.DisplayName
	}
	if b.Email != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 7, 9)
		x.xxx_hidden_Email = b.Email
	}
	if b.AnEnum != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 8, 9)
		x.xxx_hidden_AnEnum = *b.AnEnum
	}
	return m0
}

var File_v1_example_proto protoreflect.FileDescriptor

const file_v1_example_proto_rawDesc = "" +
	"\n" +
	"\x10v1/example.proto\x12\fexamplepb.v1\x1a\x16dynamo/v1/dynamo.proto\x1a!google/protobuf/go_features.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xec\x05\n" +
	"\x05Store\x12 \n" +
	"\x02id\x18\x01 \x01(\tB\x10\x82\xf7\x02\f\b\x01\x12\bstore_idR\x02id\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x16\n" +
	"\x06closed\x18\x06 \x01(\bR\x06closed\x12H\n" +
	"\fopening_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\t\x82\xf7\x02\x05\x1a\x03\xe0\x12\x01R\vopeningDate\x125\n" +
	"\x11best_employee_ids\x18\b \x03(\tB\t\x82\xf7\x02\x05\x1a\x03\xc0\f\x01R\x0fbestEmployeeIds\x125\n" +
	"\bbin_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\abinDate\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xe0\x12\x01R\texpiresAt\x12K\n" +
	"\rexpires_at_ms\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xe8\x12\x01R\vexpiresAtMs\x12K\n" +
	"\rexpires_at_ns\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xf0\x12\x01R\vexpiresAtNs\x12\x10\n" +
	"\x03foo\x18c \x01(\x04R\x03foo\x12#\n" +
	"\amorefoo\x18d \x03(\x04B\t\x82\xf7\x02\x05\x1a\x03\xc0\f\x01R\amorefoo:A\x82\xf7\x02=\x12\x1b\n" +
	"\x02id\n" +
	"\acountry\n" +
	"\x03foo\x1a\aexample\x12\x1e\n" +
	"\x02id\n" +
	"\acountry\n" +
	"\x03foo\x1a\n" +
	"dummyvalue\"\xd1\x03\n" +
	"\x04User\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x15\n" +
	"\x06idp_id\x18\x06 \x01(\tR\x05idpId\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x120\n" +
	"\aan_enum\x18\t \x01(\x0e2\x17.examplepb.v1.BasicEnumR\x06anEnum\x12\x19\n" +
	"\bshard_id\x18\n" +
	" \x01(\rR\ashardId:N\x82\xf7\x02J\x12\x15\n" +
	"\ttenant_id\x12\x02id\"\x04\b\x01\x10 \x12\x13\n" +
	"\ttenant_id\x12\x06idp_id\x12\x1c\n" +
	"\ttenant_id\x12\x06idp_id\x12\aan_enum\"\xee\x05\n" +
	"\aStoreV2\x12 \n" +
	"\x02id\x18\x01 \x01(\tB\x10\x82\xf7\x02\f\b\x01\x12\bstore_idR\x02id\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x16\n" +
	"\x06region\x18\x03 \x01(\tR\x06region\x12\x14\n" +
	"\x05state\x18\x04 \x01(\tR\x05state\x12\x12\n" +
	"\x04city\x18\x05 \x01(\tR\x04city\x12\x16\n" +
	"\x06closed\x18\x06 \x01(\bR\x06closed\x12H\n" +
	"\fopening_date\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\t\x82\xf7\x02\x05\x1a\x03\xe0\x12\x01R\vopeningDate\x125\n" +
	"\x11best_employee_ids\x18\b \x03(\tB\t\x82\xf7\x02\x05\x1a\x03\xc0\f\x01R\x0fbestEmployeeIds\x125\n" +
	"\bbin_date\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\abinDate\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12F\n" +
	"\n" +
	"expires_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xe0\x12\x01R\texpiresAt\x12K\n" +
	"\rexpires_at_ms\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xe8\x12\x01R\vexpiresAtMs\x12K\n" +
	"\rexpires_at_ns\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\v\x82\xf7\x02\a\b\x01\x1a\x03\xf0\x12\x01R\vexpiresAtNs\x12\x10\n" +
	"\x03foo\x18c \x01(\x04R\x03foo\x12#\n" +
	"\amorefoo\x18d \x03(\x04B\t\x82\xf7\x02\x05\x1a\x03\xc0\f\x01R\amorefoo:A\x82\xf7\x02=\x12\x1b\n" +
	"\x02id\n" +
	"\acountry\n" +
	"\x03foo\x1a\aexample\x12\x1e\n" +
	"\x02id\n" +
	"\acountry\n" +
	"\x03foo\x1a\n" +
	"dummyvalue\"\xc0\x03\n" +
	"\x06UserV2\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAt\x12\x15\n" +
	"\x06idp_id\x18\x06 \x01(\tR\x05idpId\x12!\n" +
	"\fdisplay_name\x18\a \x01(\tR\vdisplayName\x12\x14\n" +
	"\x05email\x18\b \x01(\tR\x05email\x120\n" +
	"\aan_enum\x18\t \x01(\x0e2\x17.examplepb.v1.BasicEnumR\x06anEnum:V\x82\xf7\x02R\x12\x0f\n" +
	"\ttenant_id\x12\x02id\x12\x1a\n" +
	"\ttenant_id\x12\x06idp_id\"\x05\b\x01\x10\x80\b\x12#\n" +
	"\ttenant_id\n" +
	"\x06idp_id\x12\aan_enum\"\x05\b\x01\x10\x80\x04*\"\n" +
	"\tBasicEnum\x12\t\n" +
	"\x05First\x10\x00\x12\n" +
	"\n" +
	"\x06Second\x10\x01B;Z1github.com/pquerna/protoc-gen-dynamo/examplepb/v1\x92\x03\x05\xd2>\x02\x10\x03b\beditionsp\xe8\a"

var file_v1_example_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_v1_example_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_example_proto_goTypes = []any{
	(BasicEnum)(0),                // 0: examplepb.v1.BasicEnum
	(*Store)(nil),                 // 1: examplepb.v1.Store
	(*User)(nil),                  // 2: examplepb.v1.User
	(*StoreV2)(nil),               // 3: examplepb.v1.StoreV2
	(*UserV2)(nil),                // 4: examplepb.v1.UserV2
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_v1_example_proto_depIdxs = []int32{
	5,  // 0: examplepb.v1.Store.opening_date:type_name -> google.protobuf.Timestamp
	5,  // 1: examplepb.v1.Store.bin_date:type_name -> google.protobuf.Timestamp
	5,  // 2: examplepb.v1.Store.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 3: examplepb.v1.Store.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 4: examplepb.v1.Store.expires_at_ms:type_name -> google.protobuf.Timestamp
	5,  // 5: examplepb.v1.Store.expires_at_ns:type_name -> google.protobuf.Timestamp
	5,  // 6: examplepb.v1.User.created_at:type_name -> google.protobuf.Timestamp
	5,  // 7: examplepb.v1.User.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 8: examplepb.v1.User.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 9: examplepb.v1.User.an_enum:type_name -> examplepb.v1.BasicEnum
	5,  // 10: examplepb.v1.StoreV2.opening_date:type_name -> google.protobuf.Timestamp
	5,  // 11: examplepb.v1.StoreV2.bin_date:type_name -> google.protobuf.Timestamp
	5,  // 12: examplepb.v1.StoreV2.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 13: examplepb.v1.StoreV2.expires_at:type_name -> google.protobuf.Timestamp
	5,  // 14: examplepb.v1.StoreV2.expires_at_ms:type_name -> google.protobuf.Timestamp
	5,  // 15: examplepb.v1.StoreV2.expires_at_ns:type_name -> google.protobuf.Timestamp
	5,  // 16: examplepb.v1.UserV2.created_at:type_name -> google.protobuf.Timestamp
	5,  // 17: examplepb.v1.UserV2.updated_at:type_name -> google.protobuf.Timestamp
	5,  // 18: examplepb.v1.UserV2.deleted_at:type_name -> google.protobuf.Timestamp
	0,  // 19: examplepb.v1.UserV2.an_enum:type_name -> examplepb.v1.BasicEnum
	20, // [20:20] is the sub-list for method output_type
	20, // [20:20] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_v1_example_proto_init() }
func file_v1_example_proto_init() {
	if File_v1_example_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_example_proto_rawDesc), len(file_v1_example_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_example_proto_goTypes,
		DependencyIndexes: file_v1_example_proto_depIdxs,
		EnumInfos:         file_v1_example_proto_enumTypes,
		MessageInfos:      file_v1_example_proto_msgTypes,
	}.Build()
	File_v1_example_proto = out.File
	file_v1_example_proto_goTypes = nil
	file_v1_example_proto_depIdxs = nil
}
