package v1_test

import (
	"testing"
	"time"

	"github.com/aws/aws-sdk-go-v2/service/dynamodb/types"
	v1 "github.com/pquerna/protoc-gen-dynamo/example/v1"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/known/timestamppb"
)

// The key stringers and the marshalled item must agree on every partition and
// sort key, sharded or not. They are generated by separate code paths, and a
// sharded GSI whose item is written with an unsharded pk can never be found by
// a query built from its stringer.
func TestMarshalledKeysMatchStringers(t *testing.T) {
	user := v1.UserV2_builder{
		TenantId:  proto.String("acme"),
		Id:        proto.String("user-1"),
		IdpId:     proto.String("okta-42"),
		Email:     proto.String("someone@example.com"),
		AnEnum:    v1.BasicEnum_Second.Enum(),
		CreatedAt: timestamppb.New(time.Unix(1700000000, 0)),
		UpdatedAt: timestamppb.New(time.Unix(1700000001, 0)),
	}.Build()

	av, err := user.MarshalDynamoDBAttributeValue()
	if err != nil {
		t.Fatalf("marshal: %v", err)
	}
	item, ok := av.(*types.AttributeValueMemberM)
	if !ok {
		t.Fatalf("expected *types.AttributeValueMemberM, got %T", av)
	}

	// gsi1 is sharded (shard_count 32), gsi2 is sharded (shard_count 64),
	// the primary key is not.
	want := map[string]string{
		"pk":     user.PartitionKey(),
		"sk":     user.SortKey(),
		"gsi1pk": user.Gsi1PkKey(),
		"gsi1sk": user.Gsi1SkKey(),
		"gsi2pk": user.Gsi2PkKey(),
		"gsi2sk": user.Gsi2SkKey(),
	}

	for attr, expected := range want {
		got, ok := item.Value[attr].(*types.AttributeValueMemberS)
		if !ok {
			t.Errorf("item[%q]: expected *types.AttributeValueMemberS, got %T", attr, item.Value[attr])
			continue
		}
		if got.Value != expected {
			t.Errorf("item[%q] = %q, stringer returned %q", attr, got.Value, expected)
		}
	}
}
